services:
  god_codes.digitletters_engine:
    class: GO\DCodesBundle\Generator\DigitsLettersGenerator\DigitsLettersEngine
    public: false

  god_codes.digitlettersgenerator:
    class: GO\DCodesBundle\Generator\DigitsLettersGenerator\DigitsLettersGenerator
    arguments: ["@god_codes.digitletters_engine"]

