services:
  god_codes.digitletters_engine:
    class: GO\DCodesBundle\Generator\DigitsLettersGenerator\DigitsLettersEngine
    public: false

  god_codes.codegenerator:
    class: GO\DCodesBundle\Generator\CodeGenerator
    arguments: ["@god_codes.digitletters_engine"]

